language :android
jdk:
 -oraclejdk8

android:
  components:
        - tools ## to get the new `repository-11.xml
        - tools
        - platform-tools
        - build-tools-25.0.3
        - android-25
        - extra
script : 
        - ./gradlew build connectedCheck
         
